{{- define "dispatcher.deployment" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    part-of: azul
    section: core
    component: dispatcher
spec:
  revisionHistoryLimit: 1
  replicas: {{ .config.replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
        part-of: azul
        section: core
        component: dispatcher
        allow-egress-s3: "true"
        allow-egress-kafka: "true"
        allow-egress-redis: "true"
        allow-ingress-dispatcher: "true"
        {{- if .root.Values.external.loki.endpoint }}
        allow-egress-loki: "true"
        {{- end }}
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8111"
        prometheus.io/scrape: "true"
        # ensure deployment restarts if config is changed
        checksum/config: {{ .cmSHA256 }}
      {{- with .root.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .root.Values.external.filestore.serviceAccountName }}
      serviceAccountName: {{ .root.Values.external.filestore.serviceAccountName }}
      {{- end }}
      {{- include "harden.deployment" . | nindent 6 }}
      containers:
      - name: main
        image: {{ include "image.custom" (dict "images" .root.Values.images "name" "dispatcher")}}
        imagePullPolicy: {{ .root.Values.images.pullPolicy }}
        {{- include "harden.container" . | nindent 8 }}
        {{- if .config.resources }}
        resources:
        {{- .config.resources | toYaml | nindent 10 }}
        {{- end }}
        {{- if eq .noProbes "false" }}
        livenessProbe:
          httpGet:
            path: /
            port: 8111
          initialDelaySeconds: 30
          periodSeconds: 30
        {{- end }}
        {{- if .config.args }}
        args: {{ .config.args }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: dispatcher
          {{- if .reprocess }}
          - configMapRef:
              name: dispatcher-reprocess
          {{- if eq .reprocess "sources"}}
          - configMapRef:
              name: dispatcher-reprocess-sources
          {{- else if eq .reprocess "system" }}
          - configMapRef:
              name: dispatcher-reprocess-system
          {{- else }}
            {{- fail (printf "bad reprocess type: %s" .reprocess) }}
          {{- end }}
          {{- end }}
        env:
          {{- if not .root.Values.external.filestore.serviceAccountName }}
          {{- if eq "s3" (.root.Values.external.filestore.backend | lower) }}
          - name: DP.STREAMS.S3.ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.filestore }}
                key: accesskey
          - name: DP.STREAMS.S3.SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.filestore }}
                key: secretkey
          {{- else if eq "azure" (.root.Values.external.filestore.backend | lower) }}
          - name: DP.STREAMS.AZURE.ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.filestore }}
                key: accesskey
                optional: true
          # Needed by the go package that does azure authentication if you are using authorized applications.
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.filestore }}
                key: clientsecret
                optional: true
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.filestore }}
                key: clientId
                optional: true
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.filestore }}
                key: tenantId
                optional: true
          {{- end }}
          {{- end }}
          - name: DP.EVENTS.REDIS.USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.redis }}
                key: redis-username
          - name: DP.EVENTS.REDIS.PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .root.Values.secrets.redis }}
                key: redis-password
          - name: DP.STREAMS.FCACHE.PATH
            value: "/fcache"
          - name: GODEBUG
            value: madvdontneed=1
          - name: GOGC
            value: "50"
          {{- /* Add a GOMEMLIMIT if there isn't already one set in ENV. */}}
          {{- if not (and .config.env .config.env.GOMEMLIMIT) }}
            {{- /* This converts from Kubernetes resource.memory format to the GOMEMLIMIT in bytes. */}}
            {{- $memLimitVal := coalesce .config.resources.limits.memory .config.resources.requests.memory false -}}
            {{- if $memLimitVal }}
            {{- $multiplier := ternary 1024 1000 (hasSuffix "i" $memLimitVal) -}}
            {{- /* Default case of Bytes (remove any letters) */}}
            {{- $memLimitInt := regexReplaceAll "[a-z]*[A-Z]*" $memLimitVal "" -}}
            {{- /* Multiply by multipler based on the unit (kiloBytes vs GigaBytes etc.) */}}
            {{- if regexMatch "k" $memLimitVal }}
            {{- $memLimitInt = mul $memLimitInt $multiplier }}
            {{- else if regexMatch "M" $memLimitVal }}
            {{- $memLimitInt = mul $memLimitInt $multiplier $multiplier }}
            {{- else if regexMatch "G" $memLimitVal }}
            {{- $memLimitInt = mul $memLimitInt $multiplier $multiplier $multiplier }}
            {{- else if regexMatch "T" $memLimitVal }}
            {{- $memLimitInt = mul $memLimitInt $multiplier $multiplier $multiplier $multiplier }}
            {{- end }}
            {{- /* Limit memory limit to 90% of the available memory. */}}
          - name: GOMEMLIMIT
            value: {{ mulf 0.90 $memLimitInt | int }}B
            {{- end }}
          {{- end }}
          {{- range $k, $v := .config.env }}
          - name: {{ $k }}
            value: "{{ $v }}"
          {{- end}}
        ports:
          - name: http
            containerPort: 8111
        volumeMounts:
          - name: tmp
            mountPath: /tmp/
          - name: tmp-file-cache
            mountPath: "/fcache"
          - name: logs
            mountPath: "/logs"
          {{- if .root.Values.CACertificateConfigMap }}
          - mountPath: /etc/ssl/certs/ca-certificates.crt
            name: ca-cert
            subPath: ca.crt
          {{- end }}
      {{- if .root.Values.external.loki.endpoint }}
      - name: alloy
        image: {{ get .root.Values.images.external "alloy" | required "missing image for alloy" }}
        {{- include "harden.container" . | nindent 8 }}
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "500m"
        args:
          - run
          - /etc/alloy/config.river
          - --storage.path=/data/alloy
        volumeMounts:
          - name: {{ .name }}-alloy
            mountPath: /etc/alloy
          - name: logs
            mountPath: "/logs"
          - name: alloy-data
            mountPath: /data/alloy
      {{- end }}
      {{- if .config.topologySpreadConstraints }}
      {{- $name := .name }}
      topologySpreadConstraints:
        {{- range .config.topologySpreadConstraints }}
        - labelSelector:
            matchLabels:
              app: {{ $name }}
          {{- . | toYaml | nindent 10 }}
        {{- end }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 200Mi
      - name: tmp-file-cache
        emptyDir:
          sizeLimit: 10Gi
      # FUTURE fix loki integration to get logs out reliably, or use statefulsets for restapi, with PVCs
      - name: logs
        emptyDir:
          sizeLimit: 200Mi
      - name: alloy-data
        emptyDir:
          sizeLimit: 200Mi
      {{- if .root.Values.CACertificateConfigMap }}
      - name: ca-cert
        configMap:
          name: {{ .root.Values.CACertificateConfigMap }}
      {{- end }}
      - name: {{ .name }}-alloy
        configMap:
          name: {{ .name }}-alloy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-alloy
data:
  config.river: |
    local.file_match "{{ replace .name "-" "_" }}" {
      path_targets = [{
        __address__ = "localhost",
        __path__    = "/logs/*.log",
        app         = "{{ .name }}",
        component   = "frontend",
        namespace   = "{{ .root.Release.Namespace }}",
        section     = "core",
      }]
    }

    loki.source.file "{{ replace .name "-" "_" }}" {
      targets               = local.file_match.{{ replace .name "-" "_" }}.targets
      forward_to            = [loki.write.default.receiver]
      legacy_positions_file = "/logs/positions.yaml"
    }

    loki.write "default" {
      endpoint {
        url = "{{ .root.Values.external.loki.endpoint }}/loki/api/v1/push"
      }
      external_labels = {}
    }

{{- end }}